<?php

namespace MediaRemoteBundle\Repository;

use MediaRemoteBundle\Entity\Remote;
use MediaRemoteBundle\Entity\MediaRemote;
use MediaRemoteBundle\Entity\Media;



/**
 * MediaRemoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRemoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRemoteNameAndMediaName(string $remoteName, string $mediaName)
    {
        return $this->findOneBy([
        "remote" => $this
            ->getEntityManager()
            ->getRepository(Remote::class)
            ->findOneByRemoteName($remoteName),
        "media" => $this
            ->getEntityManager()
            ->getRepository(Media::class)
            ->findOneByMediaName($mediaName),
        ]);
    }


    public function findByRemoteName(string $name): array
    {
        $remote = $this->getEntityManager()
            ->getRepository(Remote::class)
            ->findOneByRemoteName($name);
        return $this->findByRemote($remote);
    }

    public function findDefaultRemoteName(): string
    {
        return $this->getEntityManager()
            ->getRepository(Remote::class)
            ->findOneBy([])
            ->getRemoteName();
    }

    public function findByMediaName(string $name): array
    {
        $remote = $this->getEntityManager()
            ->getRepository(Remote::class)
            ->findOneByRemoteName($name);
        return $this->findByMedia($remote);
    }
}
